version: '3'
services:
  mongo:
    image: mongo:3.6
  
  
  web:
    build: .
    ports:
     - "9000:9000"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test 
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/starter
     - /starter/node_modules

  nginx:
    build:
      context: .
      dockerfile: nginx/nginx.dockerfile
    links:
      - web:web  
    depends_on:
      - web
    ports:
      - "3333:80"
  